### ISSUE TITLE
fix texture display bug

### ISSUE THREAD

**Issue by elect-gombe** [elect-gombe/k210_mmd#1]
テクスチャ表示が化けるのを直す。
原因として考えられるのが、テクスチャ座標の計算のオーバフローだと思うんだが実際わからん

**Comment by xelll** [comment]
you can add a compile-flag -ffloat-store, maybe it cause the bug

**Comment by vowstar** [comment]
## たぶんあなたが使うことができる方法

> 実際、うまくいくかどうかはわかりません

### 一時的に修正するには不完全な方法がありますA:

1. 最新のSDKを使う

```
git clone https://github.com/kendryte/kendryte-standalone-sdk
git checkout 62917aeea98fccfa47eb6602f05ecbfe509bb7c4
```
2. RISC-VコンパイラD拡張（"D"は倍精度浮動小数点命令）を無効にする

```-march=rv64imafc```を```add_compile_flags```に追加

https://github.com/kendryte/kendryte-standalone-sdk/blob/develop/cmake/compile-flags.cmake

```
add_compile_flags(BOTH
        -mcmodel=medany
        -march=rv64imafc
        -fno-common
        -ffunction-sections
        -fdata-sections
        -fstrict-volatile-bitfields
        -fno-zero-initialized-in-bss
        -Os
        -ggdb
        )
```

3. そしてこのツールチェーンを使う

https://github.com/kendryte/kendryte-gnu-toolchain/releases/tag/v8.2.0-20190213

4. 再コンパイルとテスト

### 一時的に修正するには不完全な方法がありますB:

このツールチェーンで直接コンパイルする

https://github.com/kendryte/kendryte-gnu-toolchain/releases/tag/v8.2.0-20190221

多分それは大丈夫だろう

**Comment by elect-gombe** [comment]
Using latest toolchain at development branch, it works just fine! thank you.
