### ISSUE TITLE
initialization issue ( window_height  / pll_set_freq )

### ISSUE THREAD

**Issue by MrJBSwe** [elect-gombe/k210_mmd#2]
Nice work !!

There seems to be some initialization issue related to height and frequency !?

window_height = 220; // above 220 unstable, can't get it to work on 240

below unstable 
 sysctl_pll_set_freq(SYSCTL_PLL0, 480000000UL);

**Comment by elect-gombe** [comment]
Overclocking is sometimes unstable, so I decided not to overclock in default configulation.
is there any this screen height problem? let me know about it more.
